//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class book_reviews
    {
        public int review_id { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> user_id { get; set; }
        [Required(ErrorMessage = "Rating is required.")]
        public Nullable<int> rating { get; set; }
        [Required(ErrorMessage = "Comment is required.")]
        public string comment { get; set; }
        public Nullable<System.DateTime> review_timestamp { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
