//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.book_reviews = new HashSet<book_reviews>();
            this.borrowing_record = new HashSet<borrowing_record>();
            this.reservations = new HashSet<reservation>();
        }
    
        public string ISBN { get; set; }

        [Required(ErrorMessage = "Title is required.")]
        public string title { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> publisher_id { get; set; }
        public string genre_name { get; set; }

        [Required(ErrorMessage = "Total Copies are required.")]
        public Nullable<int> totalCopies { get; set; }
        public Nullable<int> borrowedCopies { get; set; }
     
        public Nullable<int> avlCopies { get; set; }
        [Required(ErrorMessage = "Publication Year is required.")]
        public Nullable<int> publication_year { get; set; }
    
        public virtual author author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book_reviews> book_reviews { get; set; }
        public virtual genre genre { get; set; }
        public virtual publisher publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrowing_record> borrowing_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
