//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class borrowing_record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public borrowing_record()
        {
            this.fines = new HashSet<fine>();
        }
    
        public int borrowing_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> borrow_timestamp { get; set; }
        public Nullable<System.DateTime> due_timestamp { get; set; }
        public Nullable<System.DateTime> return_timestamp { get; set; }
        [Required(ErrorMessage = "Status is required.")]
        public string status { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fine> fines { get; set; }
    }
}
