//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class fine
    {
        public int fine_id { get; set; }
        public Nullable<int> borrowing_id { get; set; }
        [Required(ErrorMessage = "Amount is required.")]
        public Nullable<decimal> fine_amount { get; set; }
        [Required(ErrorMessage = "Due Timestamp is required.")]
        public Nullable<System.DateTime> fine_due_timestamp { get; set; }
        [Required(ErrorMessage = "Status is required.")]
        public string fine_status { get; set; }
    
        public virtual borrowing_record borrowing_record { get; set; }
    }
}
