//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class login_history
    {
        public int login_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public Nullable<System.DateTime> logout_time { get; set; }
        [Required(ErrorMessage = "IP Address is required.")]
        public string ip_address { get; set; }
    
        public virtual user user { get; set; }
    }
}
