//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSEntities : DbContext
    {
        public LMSEntities()
            : base("name=LMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<book_reviews> book_reviews { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<borrowing_record> borrowing_record { get; set; }
        public virtual DbSet<fine> fines { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<login_history> login_history { get; set; }
        public virtual DbSet<publisher> publishers { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user_contacts> user_contacts { get; set; }
        public virtual DbSet<user> users { get; set; }

    }
}
