//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int reservation_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> reservation_timestamp { get; set; }
        public Nullable<System.DateTime> expiration_timestamp { get; set; }
        public string reservation_status { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
